### ISSUE TITLE
使用 maptalks.wmts 加载天地图墨卡托投影错乱

### ISSUE THREAD

**Issue by shmen** [lifefriend/maptalks-demo#3]
使用maptalks.wmts加载天地图墨卡托投影错乱

`var wMTSTileLayer = new maptalks.WMTSTileLayer('base', {
            tileSystem : [1, -1, -180, 90],
            layer:'vec',
            tilematrixset:'w',
            format:'tiles',
            urlTemplate:'http://t{s}.tianditu.com/vec_w/wmts?tk=YOUR_TK_KEY',
            subdomains:['1', '2', '3', '4', '5'],
            attribution : '&copy; <a target="_blank" href="http://www.tianditu.cn">Tianditu</a>'
          }).addTo(map);`

**Comment by lifefriend** [comment]
墨卡托投影需要指定 projection 为 3857，然后删除tileSystem
```javascript
var map = new maptalks.Map('map', {
          spatialReference:{
            projection:'EPSG:3857'
          }
}
new maptalks.WMTSTileLayer('base', { 
            layer: 'vec', 
            tilematrixset: 'w', 
            format: 'tiles', 
            urlTemplate: 'http://t{s}.tianditu.com/vec_w/wmts?=YOUR_TK_KEY', 
            subdomains: ['1', '2', '3', '4', '5'], 
            attribution: '&copy; <a target="_blank" href="http://www.tianditu.cn">Tianditu</a>' 
 }).addTo(map)
```

**Comment by lifefriend** [comment]
close
